# Site settings
title: HealthyU
email: dabennett@ua.edu
description: > # this means to ignore newlines until "baseurl:"
  A Campus-Wide Running Challenge
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  healthy-u

sass:
    style: compressed

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

#defaults:
#    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title'}}

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
